---
name: "ActiveStreams"
guid: "be82ad29-cc88-4d5e-8149-ff122975a52b"
version: "1.0.0.0"
targetAbi: "10.11.0"
framework: "net8.0"
overview: "Show active streams"
description: "Show active streams."
category: "General"
owner: "TeKo"
artifacts:
- "Jellyfin.Plugin.ActiveStreams.dll"
changelog: >
  changelog
